---
title: "Mini Report"
date: "2024-06-25"
output:
  html_document: default
---
```{r setup, include=FALSE}
wd<- "C:/Users/EshaSharma/Onedrive - EshaSharma/OneDrive - Genective/Desktop/R Studio/IVE_RCode/Data"
knitr::opts_knit$set(root.dir = wd)
```

```{r, include=FALSE, warning=FALSE}
library(readxl)
library(openxlsx)
library(tidyverse)
library(openxlsx)
library(gt)
```

```{r, echo=FALSE, results='asis'}
ri<-read.xlsx("Report Information.xlsx")
blank<-""

report.date<-"2/23/2024"
experiment.ID<-"240215_UNI_PRMY_ WC_CEW_FAW_SCB_WCR_ Plate_458_OLDWAY"
samples.submission.date<-"2/15/2024"
objective<-"Primary Screen-Test 1"
species<-"CEW"

trial.setup.date<-"2/15/2024"
trial.completion.date<-"2/23/2024"
insect.source<-"Benzon"

submittor<-"Madison"
project<-"Metagenomics and Uniprot"

ri$B<-c(report.date,experiment.ID,samples.submission.date,objective,species)
ri$D<-c(trial.setup.date,trial.completion.date,insect.source,blank,blank)
ri$F<-c(submittor,project,blank,blank,blank)

info_gt<-gt(ri)
info_gt<-
    info_gt |>
    tab_options(column_labels.hidden = TRUE
    ) |>
    opt_table_lines("all"
    ) |>
    opt_horizontal_padding(scale = 3
    ) |>
    sub_missing(missing_text = ""
    ) |>
    tab_style(
        style = list(
            cell_text(weight = "bold")
        ),
        locations = cells_body(
            columns = c("A","C","E")
        )
    )

info_gt

```

```{r, include=FALSE, warning=FALSE}
getwd()
data<-read_excel("exdata.xlsm", sheet = "Graphs", col_names = FALSE)
newcols<-read.xlsx("Table.xlsx")
```

```{r, include=FALSE, warning=FALSE}
# Create a dataframe for each bug
CEW<- data %>% slice(1:32)
SCB<- data %>% slice(51:82)
sFAW<- data %>% slice(103:134)
rFAW<- data %>% slice(155:186)
SWCB<- data %>% slice(207:238)
sWCR<- data %>% slice(259:290)
rWCR<- data %>% slice(311:342)

```

```{r, include=FALSE, warning=FALSE}
#gets today's date and formats into YYMMDD
date <-Sys.Date()
year <- format(date, format="%y")
month <- format(date, format="%m")
day <- format(date, format="%d")
date <-paste(year, month, day, sep="")
date2 <- paste(month, day, year, sep=".")

#Create a sub folder for new excel files and set as new working directory
folder <- paste("Mini Report Files", date2, sep="-")
dir.create(folder)
new_wd <- paste(wd, folder, sep= "/")
```


```{r, include=FALSE, warning=FALSE}
setwd(new_wd)
getwd()
#Format Dataframes and save as new excel files
library(openxlsx)

Bugs <- list(CEW,SCB,sFAW,rFAW,SWCB,sWCR,rWCR)

for (bug in Bugs) {
    y<- bug[1,1]
    y<- as.character(y)
    names(bug)<-bug[2,]
    x<-bug %>% slice(3:32)
    x <- x %>% mutate_at(c("Dead","Unaffected","Stunted","Slightly Stunted","% Average mortality","% Error"), as.numeric)
    if (sum(x$Unaffected)==0) next
    x <- x %>% mutate(newcols)
    x$Bug <- y
    x$Bug <- as.character(x$Bug)
    write.xlsx(x,file = paste(bug[1,1],".xlsx"))
}

#List files in folder
DataList<-list.files(path = new_wd,    
                     pattern = "*.xlsx",
                     full.names = FALSE)

# Add columns of statistics to each individual file
for (File in DataList) {
    wb<-loadWorkbook(File) #Read in file
    x<-read.xlsx(File) #Read in data
    x<- x %>% mutate(n = Dead+Unaffected+Stunted+Slightly.Stunted)
    x<- x %>% mutate(Mortality = Dead/n)
    x<- x %>% mutate(Stunted.p = Stunted/n)        
    x<- x %>% mutate(Slightly.Stunted.p = Slightly.Stunted/n)
    write.xlsx(x,File,rowNames = FALSE) #Paste transformed data back into file
}

# Formatting data frames

Order <- c(26,27,28,29,30,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,1)

for (File in DataList) {
    wb<-loadWorkbook(File)
    df<-read.xlsx(File)
    df<- df %>% mutate(Order)
    df<- df %>% arrange(Order)
    df<- df %>% relocate(Bug,.before = Sample)
    write.xlsx(df,File,rownames = FALSE)
}

```

```{r, echo=FALSE, results='asis'}
setwd(new_wd)

cnames<- c("Description","Sample ID","n","Dose","Slight Stunting Score","Stunting Score","Mortality Score","% Contamination","Stats(if relevant)")

for (File in DataList) {
    wb<-loadWorkbook(File)
    df<-read.xlsx(File)
    bug<-df[1,1]
    df_graph <- df %>% select(Description,Sample,n,Dose,Slightly.Stunted.p,Stunted.p,Mortality,'%.Contamination','Stats.(if.relevant)')
    colnames(df_graph)<-cnames
    gt_df<-gt(df_graph)
    gt_df <-
        gt_df |>
        tab_header(
            title = paste(bug)
        ) |>
        tab_row_group(
            label = md("**IVE internal controls**"),
            rows = 26:30
        ) |>
        row_group_order(
            groups = c(NA,"**IVE internal controls**")
        ) |>
        fmt_percent(
            columns = c("Slight Stunting Score","Stunting Score","Mortality Score","% Contamination"),
            decimals = 2
        ) |>
        opt_stylize(
            style = 2,
            color = "blue"
        )
    print(gt_df)
}


```
