---
title: "Untitled"
author: "me"
date: "2024-06-25"
output:
  word_document: default
  html_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
wd<- "C:/Users/EshaSharma/Onedrive - EshaSharma/OneDrive - Genective/Desktop/R Studio/IVE_RCode/Data"
knitr::opts_knit$set(root.dir = wd)
```

```{r, include=FALSE, warning=FALSE}
library(readxl)
library(openxlsx)
library(tidyverse)
library(openxlsx)
library(gt)
```

```{r, echo=FALSE, results='asis'}
ri<-read.xlsx("Report Information.xlsx")
blank<-""

report.date<-"2/23/2024"
experiment.ID<-"240215_UNI_PRMY_WC_CEW_FAW_SCB_WCR_Plate_458_OLDWAY"
samples.submission.date<-"2/15/2024"
objective<-"Primary Screen-Test 1"
species<-"CEW"

trial.setup.date<-"2/15/2024"
trial.completion.date<-"2/23/2024"
insect.source<-"Benzon"

submittor<-"Madison"
project<-"Metagenomics and Uniprot"

ri$B<-c(report.date,experiment.ID,samples.submission.date,objective,species)
ri$D<-c(trial.setup.date,trial.completion.date,insect.source,blank,blank)
ri$F<-c(submittor,project,blank,blank,blank)

info_gt<-gt(ri)
info_gt<-
    info_gt |>
    tab_options(column_labels.hidden = TRUE
    ) |>
    opt_table_lines("all"
    ) |>
    opt_horizontal_padding(scale = 3
    ) |>
    sub_missing(missing_text = "")

as_word(info_gt)

```